INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (109.95, 120, 0, current_timestamp, NULL, 'FA-001', 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',                        'system admin', 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', NULL, 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (22.3, 259, 0,   current_timestamp, NULL, 'FA-002', 'Mens Casual Premium Slim Fit T-Shirts',                                        'system admin', 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', NULL, 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (55.99, 500, 0,  current_timestamp, NULL, 'FA-003', 'Mens Cotton Jacket',                                                           'system admin', 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', NULL, 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (15.99, 430, 0,  current_timestamp, NULL, 'FA-004', 'Mens Casual Slim Fit',                                                         'system admin', 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', NULL, 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (695.00, 400, 0, current_timestamp, NULL, 'FA-005', 'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 'system admin', 'From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean''s pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.', NULL, 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (168.00, 70, 0,  current_timestamp, NULL, 'FA-006', 'Solid Gold Petite Micropave',                                                  'system admin', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', NULL, 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (9.99, 400, 0,   current_timestamp, NULL, 'FA-007', 'White Gold Plated Princess',                                                   'system admin', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day...', NULL, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (10.99, 100, 0,  current_timestamp, NULL, 'FA-008', 'Pierced Owl Rose Gold Plated Stainless Steel Double',                          'system admin', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', NULL, 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (64.00, 203, 0,  current_timestamp, NULL, 'FA-009', 'WD 2TB Elements Portable External Hard Drive - USB 3.0',                       'system admin', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', NULL, 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg');
INSERT INTO products (price, stock, version, created_at, updated_at, sku, name, created_by, description, updated_by, image_src) VALUES (109.00, 470, 0, current_timestamp, NULL, 'FA-010', 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',                          'system admin', 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', NULL, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg');

INSERT INTO members (version, created_at, updated_at, phone, name, email, password, created_by, updated_by) VALUES (0, current_timestamp, NULL, '0906770035', 'system admin', 'system_admin@e-commerce.org', '$2a$10$eYcuJD9FzL0X6t3WQJ3Ub.u33S7jWOKqrVWEgHnpbXwPoDoH4VRQW', 'system admin', NULL);
INSERT INTO members (version, created_at, updated_at, phone, name, email, password, created_by, updated_by) VALUES (0, current_timestamp, NULL, '0923656990', 'normal member', 'normal_member@e-commerce.org', '$2a$10$pSwvO3Rv5Fxx5jUW4XYVkup/Nl7ocdV9/yus.UODqvGIFb9U0Sifm', 'system admin', NULL);
INSERT INTO members (version, created_at, updated_at, phone, name, email, password, created_by, updated_by) VALUES (0, current_timestamp, NULL, '0923609277', 'product seller', 'product_seller@e-commerce.org', '$2a$10$.va11DNVT.sJQhdAKvjuF.BSWgvqaIW6FfSY9V201GEM386GnfWYK', 'system admin', NULL);

INSERT INTO roles (version, created_at, updated_at, created_by, name, updated_by) VALUES (0, current_timestamp, null, 'system admin', 'ROLE_SYSTEM_ADMIN', null);
INSERT INTO roles (version, created_at, updated_at, created_by, name, updated_by) VALUES (0, current_timestamp, null, 'system admin', 'ROLE_NORMAL_MEMBER', null);
INSERT INTO roles (version, created_at, updated_at, created_by, name, updated_by) VALUES (0, current_timestamp, null, 'system admin', 'ROLE_PRODUCT_SELLER', null);

INSERT INTO member_role (member_id, role_id) VALUES (1, 1);
INSERT INTO member_role (member_id, role_id) VALUES (2, 2);
INSERT INTO member_role (member_id, role_id) VALUES (3, 3);

INSERT INTO orders (order_date, total_amount, version, created_at, updated_at, buyer_email, created_by, order_number, updated_by) VALUES (current_date, 1099.50, 0, current_timestamp, null, 'normal_member@e-commerce.org', 'system admin', 'MA2024060819110118234', null);
INSERT INTO orders (order_date, total_amount, version, created_at, updated_at, buyer_email, created_by, order_number, updated_by) VALUES (current_date, 1545.50, 0, current_timestamp, null, 'normal_member@e-commerce.org', 'system admin', 'MA2024060819113108550', null);
INSERT INTO orders (order_date, total_amount, version, created_at, updated_at, buyer_email, created_by, order_number, updated_by) VALUES (current_date, 3222.20, 0, current_timestamp, null, 'normal_member@e-commerce.org', 'system admin', 'MA2024060819123104104', null);

INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (1099.50, 10, 0, current_timestamp, 1, null, 'FA-001', 'system admin', null, 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (1099.50, 10, 0, current_timestamp, 2, null, 'FA-001', 'system admin', null, 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (446.00, 20, 0,  current_timestamp, 2, null, 'FA-002', 'system admin', null, 'Mens Casual Premium Slim Fit T-Shirts', 22.3, 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg');
INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (1099.50, 10, 0, current_timestamp, 3, null, 'FA-001', 'system admin', null, 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 109.95, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg');
INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (446.00, 20, 0,  current_timestamp, 3, null, 'FA-002', 'system admin', null, 'Mens Casual Premium Slim Fit T-Shirts', 22.3, 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg');
INSERT INTO order_items (amount, quantity, version, created_at, order_id, updated_at, sku, created_by, updated_by, name, price, image_src) VALUES (1679.70, 30, 0, current_timestamp, 3, null, 'FA-003', 'system admin', null, 'Mens Cotton Jacket', 55.99, 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg');
